### ISSUE TITLE
船牌数据收集

### ISSUE THREAD

**Issue by NarcissusInMirror** [NarcissusInMirror/DailyWorkLog#8]
# 船牌数据集采集记录

| 日期 | 已标注/筛选数量 | 备注 | 星期
| ------ | ------ | ------ | ------ |
| 9.1 | 0/69 | 全天 | 周二 |
| 9.2 | 0/88 | 上午 + 五点后 |
| 9.3 | 0/45 | 凌晨 + 2：30以后 上午摄像头掉线 |
| 9.4 | 0/147 | 全天 |
| 9.5 | 0/85 | 全天 |
| 9.6 | 0/0 | 集群掉电 |
| 9.7 | 0/0 | 集群掉电 | 周一|
| 9.8 | 0/0| 集群掉电，网络故障，收集到十分钟的 |
| 9.9 | 0/107| 10点后 |
| 9.10| 0/101 | 全天;一共有3500多张图 大部分都是固定场景下的误检 |
| 9.11 | 0/166 | 全天；对比了YOLOv5和SSD半天的性能，YOLOv5 56张，SSD49张 |
| 9.12 |  | 全天 |
| 9.13 |  | 全天 |
| 9.14 |  | 全天 | 周一|
| 9.15 | 0/167 | 至下午4：30 网络中断；对比了YOLOv5和SSD全天（至下午4：30）的性能，YOLOv5 167张，SSD135张 | 周一|

**Comment by FeiSong123** [comment]
你好，请问可以分享采集的数据集吗
